### ISSUE TITLE
bootstrap.less not found

### ISSUE THREAD

**Issue by XRyu** [divshot/themestrap#1]
Got an Error that the bootstrap less wasnt found by grunt.

> File "less/variables.less" changed.
> 
> Running "copy:bootstrap" (copy) task
> 
> Running "less:compile" (less) task
> FileError: 'bootstrap.less' wasn't found in less/theme.less on line 12, column 1:
> 11 
> 12 @import "bootstrap.less";
> 13
> Warning: Error compiling LESS. Use --force to continue.
> 
> Aborted due to warnings.
> Completed in 0.531s at Tue Aug 06 2013 23:16:48 GMT+0200 (CEST) - Waiting...
> OK

i just found that i had to remove the "bower_" from "bower_components" in the gruntfile.coffee after that everything runs fine

**Comment by mbleigh** [comment]
@XRyu do you have `components` instead of `bower_components` as your default bower install directory in a `.bowerrc`?

**Comment by XRyu** [comment]
i dont know.. i never changed some file named .bowerrc if i remember correctly...

**Comment by XRyu** [comment]
maybe i did, i dont remember completely, i installed bower using some tutorial for using the first versions of bootstrap3

**Comment by uhbiv** [comment]
hi guys, i also ran into the same problem, having downloaded themestrap and running <code>grunt less:compile</code>. 
Solution was - as given here - renaming the bower install folder from 'components' to 'bower_components'. But why is this issue surfacing in the first place? shouldn't grunt be picking up bower install directory?

**Comment by eins78** [comment]
@uhbiv Your issue is the exact opposite of the situation described above, but anyhow you are right that it shouldn't matter since the bower directory is read from the configuration by grunt.

However, I couldn't reproduce the problem with a fresh clone of themestrap, and the current versions of bower and grunt installed. Setting a different directory in the `.bowerrc` also works as expected.

You can check for the bower directory the same way the Gruntfile does by opening a node shell in your themestrap directory and doing `require('bower').config.directory`. This should happen:

``` shell
$ cd ~/Desktop/themestrap
$ echo '{"directory":"foobar"}' > .bowerrc
$ node 
> require('bower').config.directory
'foobar'
```

Can you try this and report back?

**Comment by uhbiv** [comment]
@eins78 max, thanks for the help with diagnostics. turns out that there was a conflict between local and global install of bower. when calling grunt, it would call the global install, but when inside node <code>require('bower').config.directory</code> would call the local install (and hence return me correct contents, as read from .bowerrc). 
it was an outdated global install of bower causing the issue. the older one reads from component.json while new one looks for bower.json. updating the global bower fixed the issue.

i don't think if it is within the context of themestrap, but could somebody shed light on why grunt is using the global bower install, and not using the local install?
